"""add auth module

Revision ID: 8cdb436e8b60
Revises: e65cff328414
Create Date: 2019-11-25 02:12:47.618183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdb436e8b60'
down_revision = 'e65cff328414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='记录ID'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False, comment='更新时间'),
    sa.Column('email', sa.VARCHAR(length=100), server_default='', nullable=False, comment='用户邮箱'),
    sa.Column('name', sa.VARCHAR(length=100), server_default='', nullable=False, comment='用户名称'),
    sa.Column('hashed_password', sa.VARCHAR(length=100), server_default='', nullable=False, comment='用户密码hash'),
    sa.Column('ip', sa.VARCHAR(length=45), server_default='', nullable=False, comment='ip地址，标准格式，最长格式化'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user')
    # ### end Alembic commands ###
