"""init db

Revision ID: e65cff328414
Revises: 
Create Date: 2019-11-22 03:41:28.014068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65cff328414'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='记录ID'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP() on update CURRENT_TIMESTAMP()'), nullable=False, comment='更新时间'),
    sa.Column('ip', sa.VARCHAR(length=45), server_default='', nullable=False, comment='ip地址，标准格式，最长格式化'),
    sa.Column('ua', sa.VARCHAR(length=200), nullable=True, comment='user agent，超出长度取前200位'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index')
    # ### end Alembic commands ###
